name: Gitlint
description: Runs gitlint to check the commit messages of your repository
inputs:
  target:
    default: ""
    description: Path of the target git repository.
    required: false
  config-flags:
    description: |
      Config flags in format <rule>.<option>=<value>
      (e.g.: -c T1.line-length=80). Flag can be
      used multiple times to set multiple config values.
    required: false
  config-file:
      default: .gitlint
      description: Config file location
      required: false
  commits:
    default: HEAD
    description: The range of commit(s) (refspec or comma-separated hashes) to lint.
    required: false
  extra:
    default: ""
    description: Path to a directory or python module with extra user-defined rules
    required: false
  ignore:
    default: ""
    description: Ignore rules (comma-separated by id or name).
    required: false
  contrib:
    default: ""
    description: Contrib rules to enable (comma-separated by id or name).
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - --target
    - /github/${{ inputs.target }}
    - -C
    - ${{ inputs.config-file }}
    - -c
    - ${{ inputs.config-flags }}
    - --commits
    - ${{ inputs.commits }}
    - -e
    - ${{ inputs.extra }}
    - --ignore
    - ${{ inputs.ignore }}
    - --contrib
    - ${{ inputs.contrib }}
    - --ignore-stdin